export const GYM_EQUIPMENT_IDS = [
  "open_floor",
  "adjustable_bench",
  "flat_bench",
  "dumbbells",
  "kettlebells",
  "barbell",
  "squat_rack",
  "smith_machine",
  "cable_station",
  "lat_pulldown",
  "seated_row",
  "chest_press",
  "shoulder_press",
  "leg_press",
  "leg_extension",
  "leg_curl",
  "functional_trainer",
  "other_strength_machines",
  "pull_up_bar",
  "dip_station",
  "resistance_bands",
  "suspension_trainer",
  "medicine_balls",
  "ab_wheel",
  "sled",
  "treadmill",
  "stationary_bike",
  "rower",
  "elliptical",
  "stair_climber",
] as const;

export type GymEquipmentId = (typeof GYM_EQUIPMENT_IDS)[number];
