name: E2E

on:
  pull_request:
  workflow_dispatch:
    inputs:
      BASE_URL:
        description: "Override base URL for E2E"
        required: false
        default: ""

jobs:
  preview:
    name: Firebase Hosting Preview
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.deploy.outputs.details_url || steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy preview
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MYBODYSCAN_F3DAF || '' }}
          projectId: mybodyscan-f3daf
          channelId: pr-${{ github.event.number }}
        continue-on-error: true

  e2e:
    name: Playwright E2E
    runs-on: ubuntu-latest
    needs: [preview]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Resolve BASE_URL
        id: resolve_base
        run: |
          INPUT="${{ github.event.inputs.BASE_URL }}"
          PREVIEW="${{ needs.preview.outputs.preview_url }}"
          if [ -n "$INPUT" ]; then
            echo "url=$INPUT" >> $GITHUB_OUTPUT
          elif [ -n "$PREVIEW" ]; then
            echo "url=$PREVIEW" >> $GITHUB_OUTPUT
          else
            echo "url=https://mybodyscanapp.com" >> $GITHUB_OUTPUT
          fi

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ steps.resolve_base.outputs.url }}
        run: |
          echo "Testing BASE_URL=$BASE_URL"
          npm run test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: 'test-results/**/*.zip'
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload Playwright screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: 'test-results/**/*.png'
          if-no-files-found: ignore
          retention-days: 7
