name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_PROJECT: mybodyscan-f3daf
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Prepare Firebase credentials
        id: creds
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          MODE=""
          if [ -n "${FIREBASE_SERVICE_ACCOUNT:-}" ]; then
            KEY_PATH="$RUNNER_TEMP/firebase.json"
            if [[ "${FIREBASE_SERVICE_ACCOUNT}" == \{* ]]; then
              printf '%s' "$FIREBASE_SERVICE_ACCOUNT" > "$KEY_PATH"
            else
              printf '%s' "$FIREBASE_SERVICE_ACCOUNT" | base64 --decode > "$KEY_PATH"
            fi
            printf 'GOOGLE_APPLICATION_CREDENTIALS=%s\n' "$KEY_PATH" >> "$GITHUB_ENV"
            MODE="sa"
          elif [ -n "${FIREBASE_TOKEN:-}" ]; then
            printf 'FIREBASE_TOKEN=%s\n' "$FIREBASE_TOKEN" >> "$GITHUB_ENV"
            MODE="token"
          else
            echo "Firebase credentials missing. Add FIREBASE_SERVICE_ACCOUNT (base64 or raw JSON) or FIREBASE_TOKEN to the repo secrets." >&2
            exit 1
          fi
          printf 'FB_AUTH_MODE=%s\n' "$MODE" >> "$GITHUB_ENV"
          echo "Using Firebase auth mode: $MODE"

      - name: Install Firebase CLI
        run: npm install --global firebase-tools

      - name: Install dependencies and build web
        shell: bash
        run: |
          set -euo pipefail
          (npm ci || npm install --prefer-online)
          npm run build

      - name: Prepare Functions
        shell: bash
        run: |
          set -euo pipefail
          npm --prefix functions run ci-or-install
          npm --prefix functions run build

      - name: Deploy Functions and Hosting
        env:
          FIREBASE_PROJECT: ${{ env.FIREBASE_PROJECT }}
        shell: bash
        run: |
          set -euo pipefail
          echo "Deploying Firebase (auth mode: $FB_AUTH_MODE)"
          firebase deploy --only functions,hosting --project "$FIREBASE_PROJECT" --force
