name: Sanity Check

on:
  pull_request:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Base URL to probe (overrides SANITY_BASE_URL)'
        required: false
        default: ''

jobs:
  sanity:
    name: Build and Sanity Probe
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      SANITY_BASE_URL: ${{ secrets.SANITY_BASE_URL || 'https://mybodyscanapp.com' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies (root)
        run: npm ci

      - name: Install dependencies (functions)
        run: npm --prefix functions ci || npm --prefix functions install --prefer-online --no-audit --no-fund

      - name: Set base URL from dispatch input
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.base_url != '' }}
        run: echo "SANITY_BASE_URL=${{ inputs.base_url }}" >> $GITHUB_ENV

      - name: Build web app
        run: npm run build

      - name: Build Cloud Functions
        run: npm --prefix functions run build

      - name: Optionally deploy preview channel
        if: ${{ secrets.FIREBASE_TOKEN != '' && secrets.FIREBASE_PROJECT != '' && github.event_name == 'pull_request' }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
        run: |
          npx firebase-tools hosting:channel:deploy pr-${{ github.event.number }} \
            --project "$FIREBASE_PROJECT" \
            --json --non-interactive \
            --token "$FIREBASE_TOKEN" > preview.json
          echo "Preview deploy complete" && cat preview.json
          URL=$(node -e "console.log(JSON.parse(require('fs').readFileSync('preview.json','utf8')).result?.hosting?.url||'')")
          if [ -n "$URL" ]; then
            echo "SANITY_BASE_URL=$URL" >> $GITHUB_ENV
          fi

      - name: Run sanity check
        id: sanity
        env:
          SANITY_BASE_URL: ${{ env.SANITY_BASE_URL }}
        run: |
          echo "Probing base: ${SANITY_BASE_URL}"
          node tools/sanity-check.mjs

      - name: Comment results on PR
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        env:
          SUMMARY: ${{ steps.sanity.outputs.summary }}
          FAILURES: ${{ steps.sanity.outputs.failures }}
          SANITY_BASE_URL: ${{ env.SANITY_BASE_URL }}
        with:
          script: |
            const body = process.env.SUMMARY || `Sanity check ran. Base: ${process.env.SANITY_BASE_URL}`;
            const issue_number = context.payload.pull_request.number;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number,
              body: `\n**Sanity Check**\n\n\`${body}\``,
            });