name: Repository Triage (auth/demo/functions/health)

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install deps
        run: npm ci --prefer-online --no-audit --no-fund
      - name: Build web
        run: npm run build || true
      - name: Build functions
        run: npm --prefix functions run build || true
      - name: Run triage
        run: node tools/triage.mjs || true
      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: triage-report
          path: DOCS/TRIAGE_REPORT.md
      - name: Comment summary on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let body = "### 🔎 MyBodyScan Triage Report\n";
            if (fs.existsSync('DOCS/TRIAGE_REPORT.md')) {
              const md = fs.readFileSync('DOCS/TRIAGE_REPORT.md', 'utf8');
              const head = md.split('\n').slice(0, 120).join('\n');
              body += head + "\n\n_(Full report attached as artifact.)_";
            } else {
              body += "_No report generated (script error?). Check workflow logs._";
            }
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body,
            });
